name: Daily Book Data Update

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Create environment file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "ISBNDB_API_KEY=${{ secrets.ISBNDB_API_KEY }}" >> .env
          echo "GOOGLE_BOOKS_API_KEY=${{ secrets.GOOGLE_BOOKS_API_KEY }}" >> .env

      - name: Run scraper to update OrderOfBooks data
        run: |
          python scrape_orderofbooks.py

      - name: Run matcher to update matches
        run: |
          python match_series_final.py

      - name: Validate updated dataset
        run: |
          python validate_dataset.py

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "🤖 Daily data update - $(date +'%Y-%m-%d %H:%M:%S UTC')"
          git push

      - name: Create release notes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          echo "## 📊 Daily Update Summary" > update_summary.md
          echo "**Date:** $(date +'%Y-%m-%d %H:%M:%S UTC')" >> update_summary.md
          echo "" >> update_summary.md
          python -c "import json; data = json.load(open('matched_series_final.json')); total = len(data['wikipedia_series']); matched = sum(1 for s in data['wikipedia_series'] if s.get('orderofbooks_matches')); print(f'**Wikipedia Series:** {total}'); print(f'**Matched Series:** {matched}'); print(f'**Match Rate:** {(matched/total)*100:.1f}%')" >> update_summary.md
          echo "" >> update_summary.md
          echo "### Changes Made:" >> update_summary.md
          git log --oneline -1 >> update_summary.md

      - name: Upload artifacts
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: updated-dataset
          path: |
            matched_series_final.json
            index.json
            data/
            update_summary.md
          retention-days: 30
